<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>PHP Security Walkthrough</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }

            table {
                margin: auto;
            }

            table td {
                text-align: left;
            }

            #action {
                position: absolute;
                right: 20px;
                top: 0px;
            }
        </style>
    </head>
    <body>
        <h1>RNGCoin</h1>

        <section id="action">
            <a href="/logout">Log out</a>
            <a href="/profile">Profile</a>
        </section>

        <section id="messages">
            <?php if ( isset( $message ) ) : ?>
                <p><?php echo $message; ?></p>
            <?php endif; ?>
        </section>

        <section id="errors">
            <?php if ( isset( $error ) ) : ?>
                <p><?php echo $error; ?></p>
            <?php endif; ?>
        </section>

        <section id="main">
            <p>Welcome, <?php echo htmlspecialchars($fName); ?>!</p>
            <p>Current balance: RNG <?php echo htmlspecialchars($balance); ?></p>
            <p>Current RNGCoin value: $<span id="rng_val"><?php echo htmlspecialchars($value); ?></span></p>
            <p>Current dollar balance: $<span id="dollars"><?php echo htmlspecialchars($dollars); ?></span></p>
        </section>

        <script type="text/javascript">
            let balance = window.parseFloat('<?php echo htmlspecialchars($balance); ?>')
            let val = document.getElementById('rng_val')
            let bal = document.getElementById('dollars')

            let refresh = () => fetch('/value')
                    .then(data => data.text())
                    .then(t => {
                    	let real_value = window.parseFloat(t)
                        val.innerText = real_value
                        let current =  Math.floor(real_value * balance * 1000) / 1000
                        bal.innerText = current
                    })

            window.setInterval(refresh, 5000);
        </script>
    </body>
</html>
